### ISSUE TITLE
FSS implementation

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#186]
Hi @kb2623,

FSS implementation is not working. Please check it out.

I am attaching Traceback:

```
Traceback (most recent call last):
  File "run_fss.py", line 17, in <module>
    best = algo.run(task=task)
  File "../NiaPy/algorithms/algorithm.py", line 312, in run
    r = self.runTask(task)
  File "../NiaPy/algorithms/algorithm.py", line 292, in runTask
    xb, fxb = next(algo)
  File "../NiaPy/algorithms/algorithm.py", line 268, in runYield
    pop, fpop, dparams = self.initPopulation(task)
  File "../NiaPy/algorithms/basic/fss.py", line 237, in initPopulation
    curr_step_individual, curr_step_volitive, curr_weight_school, prev_weight_school, school = self.init_school(task)
  File "../NiaPy/algorithms/basic/fss.py", line 132, in init_school
    positions = self.generate_uniform_coordinates(task)
  File "../NiaPy/algorithms/basic/fss.py", line 110, in generate_uniform_coordinates
    for i in range(self.NP): x[i] = self.uniform(task.Lower[i], task.Upper[i], task.D)
IndexError: index 10 is out of bounds for axis 0 with size 10
```

**Comment by GregaVrbancic** [comment]
The issue was resolved in PR #233
