### ISSUE TITLE
raise ValueError('Newlines are not allowed')

### ISSUE THREAD

**Issue by carlosal1015** [NiaOrg/NiaPy#371]
**Steps to reproduce**

We will try to install [`python-niapy`](https://aur.archlinux.org/packages/python-niapy) in Arch Linux distribution. We provide an [animation](https://asciinema.org/a/XP5lP8XLDSTQJfz0ICUp6svjZ).

```console
$ docker run -it --rm archlinux:base-devel
# useradd -l -md /home/aur -s /bin/bash aur && passwd -d aur && echo 'aur ALL=(ALL) ALL' > /etc/sudoers.d/aur
# su aur
$ sudo pacman -Syyuq --noconfirm
$ cd ~
$ curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/python-niapy.tar.gz
$ tar -xvf python-niapy.tar.gz
$ cd python-niapy
$ makepkg -s --noconfirm
```

Further information about versions
```
$ pacman -Qs python
```

**Expected behavior**
Tell us what should happen.

Build successfully as before (~ 1 week ago).

**Actual behavior**
Tell us what happens instead.

We have this error, no idea how to proceed, I only looked both issues related [1](https://github.com/pypa/setuptools/issues/2893) [2](https://github.com/coderholic/pyradio/issues/146).

```python
byte-compiling /tmp/makepkg/python-niapy/pkg/python-niapy/usr/lib/python3.10/site-packages/niapy/util/repair.py to repair.cpython-310.pyc
writing byte-compilation script '/tmp/tmppbnk22ec.py'
/usr/sbin/python -Wignore:The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives:DeprecationWarning /tmp/tmppbnk22ec.py
removing /tmp/tmppbnk22ec.py
running install_egg_info
running egg_info
creating niapy.egg-info
writing niapy.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/tmp/makepkg/python-niapy/src/NiaPy-2.0.0/setup.py", line 49, in <module>
    setuptools.setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
    return orig.install.run(self)
  File "/usr/lib/python3.10/distutils/command/install.py", line 580, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/install_egg_info.py", line 34, in run
    self.run_command('egg_info')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 167, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 151, in single_line
    raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed
==> ERROR: A failure occurred in package().
```

**System configuration**

 - OS: Arch Linux
 - Python version: [3.10.1](https://archlinux.org/packages/core/x86_64/python)

**Comment by firefly-cpp** [comment]
@carlosal1015, great point, thanks for pointing this out!

@zStupan has already prepared a fix which has recently been merged to master.

Please report the progress of this task.

**Comment by carlosal1015** [comment]
Thank you, we tested from last commit `7a9d6a540eab84650ace882feacbd70feaa67ce3` and [no issues](https://asciinema.org/a/461032).
