### ISSUE TITLE
Make problem

### ISSUE THREAD

**Issue by kb2623** [NiaOrg/NiaPy#394]
**Steps to reproduce**
`make test`

**Expected behavior**
It should run the tests.

**Actual behavior**
Could not test the code.

**System configuration**

 - OS: Linux Garuda XenMod
 - Python version: 3.10.8

**Comment by firefly-cpp** [comment]
Makefile needs a refreshment probably.

Anyway, try with the following command: **pytest**

**Comment by kb2623** [comment]
Ouput of `make doctor`:
```
bin/verchew

Checking for Make...

$ make --version
GNU Make 4.3
~ MATCHED: GNU Make

Checking for Python...

$ python --version
Python 3.10.8
? EXPECTED: Python 3.6.

Checking for pipenv...

$ pipenv --version
pipenv, version 2022.10.4
x EXPECTED: 9.

Checking for pandoc...

$ pandoc --version
sh: command not found: pandoc
? EXPECTED: 1.
* MESSAGE: This is only needed to generate the README for PyPI.

Checking for Graphviz...

$ dot -V
sh: command not found: dot
? EXPECTED: 2.
* MESSAGE: This is only needed to generate UML diagrams for documentation.

Results: ~ ? x ? ?
```

**Comment by zStupan** [comment]
It's a problem with dependency versions, linting is also broken. Will fix ASAP.

**Comment by zStupan** [comment]
In #395 I updated the dependency versions of all packages related to flake and pytest. Linting now works, but pytest still doesn't work. I get the following error caused by the testmon plugin:

```
pipenv run pytest --testmon -ra -vv --random --random-seed=1668856719 --cov=niapy --no-cov-on-fail --cov-report=term-missing:skip-covered --cov-report=html niapy tests
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/testmon/pytest_testmon.py", line 189, in pytest_configure
INTERNALERROR>     init_testmon_data(config)
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/testmon/pytest_testmon.py", line 133, in init_testmon_data
INTERNALERROR>     testmon_data.determine_stable()
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/testmon/testmon_core.py", line 240, in determine_stable
INTERNALERROR>     filenames_fingerprints = self.db.filenames_fingerprints()
INTERNALERROR>   File "/home/zstupan/Documents/NiaPy/.venv/lib/python3.10/site-packages/testmon/db.py", line 293, in filenames_fingerprints
INTERNALERROR>     cursor = self.con.execute(
INTERNALERROR> sqlite3.OperationalError: no such column: f.filename
```

This will also cause CI to fail. I used the latest version of pytest-testmon and the error is still there, I don't think there's much else we can do on our part. Maybe we should remove testmon temporarily.
