### ISSUE TITLE
Dataframe to Excel -- not working

### ISSUE THREAD

**Issue by firefly-cpp** [NiaOrg/NiaPy#396]
Let's call runner with the following settings: runner.run(export='xsl', verbose=True) .

Issue:
**dataframe.to_excel(self.__generate_export_name("xls"))
Traceback (most recent call last):
  File "compare-algorithms.py", line 41, in <module>
    runner.run(export='xsl', verbose=True)
  File "/usr/lib/python3.11/site-packages/niapy/runner.py", line 147, in run
    self._export_to_xls()
  File "/usr/lib/python3.11/site-packages/niapy/runner.py", line 90, in _export_to_xls
    dataframe.to_excel(self.__generate_export_name("xls"))
  File "/usr/lib64/python3.11/site-packages/pandas/core/generic.py", line 2284, in to_excel
    formatter.write(
  File "/usr/lib64/python3.11/site-packages/pandas/io/formats/excel.py", line 834, in write
    writer = ExcelWriter(  # type: ignore[abstract]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pandas/io/excel/_xlwt.py", line 39, in __init__
    import xlwt
ModuleNotFoundError: No module named 'xlwt'**

Summary:

xlwt library is archived. We have included openpyxl in dependencies, but it is not used correctly.

**Comment by firefly-cpp** [comment]
One corresponding test may be added when this issue is fixed to identify this much before in the future.

**Comment by zStupan** [comment]
The issue is caused by a typo here:
https://github.com/NiaOrg/NiaPy/blob/4fdd7cc522bebe1d1b0ed5e13076d30c41078872/niapy/runner.py#L95
"xslx" should be "xlsx".
