### ISSUE TITLE
Trying to initialise IL-SHADE (DE) method with known feasible points, running into problem when inits are given as arrays

### ISSUE THREAD

**Issue by neildhir** [NiaOrg/NiaPy#619]
First, thanks for a great package.

**Steps to reproduce**

I want to initialize the population of the IL-SHADE method with a set of feasible points in numpy ndarray and array format. Here is a working MWE based on the [example in the documentation](https://niapy.org/en/stable/getting_started.html) which talks about custom population initialization.

```[python]
import numpy as np
from niapy.task import Task
from niapy.problems import Problem
from niapy.algorithms.basic import ParticleSwarmAlgorithm

# our custom Problem class
class MyProblem(Problem):
    def __init__(self, dimension, lower=-10, upper=10, *args, **kwargs):
        super().__init__(dimension, lower, upper, *args, **kwargs)

    def _evaluate(self, x):
        return np.sum(x ** 2)

# custom population initialization function
def my_init_array(task, population_size, rng, **kwargs):
    pop = np.random.uniform(task.lower, task.upper, (population_size, task.dimension))
    fpop = np.random.uniform(size=(population_size,))
    return pop, fpop

# custom population initialization function
def my_init(task, population_size, rng, **kwargs):
    pop = 0.2 + rng.random((population_size, task.dimension)) * task.range
    fpop = np.apply_along_axis(task.eval, 1, pop)
    return pop, fpop

# we will run 10 repetitions of PSO against our custom MyProblem problem function
my_problem = MyProblem(dimension=3)
task = Task(problem=my_problem, max_iters=100)
algorithm = ParticleSwarmAlgorithm(population_size=7, w=0.9, c1=0.5, c2=0.3, min_velocity=-1, max_velocity=1, initialization_function=my_init)

# running algorithm returns best found minimum
best_x, best_fit = algorithm.run(task)
print(best_fit)
```

**Expected behavior**

It should work as described in the documentation.

**Actual behavior**

If you run the above MWE with `my_init`, the same as in your documentation, it works as expected.  If you swap it out for the `my_init_array` it also works as expected.

The output shape and type of both methods are the same, but the internals of both functions are different. But `ParticleSwarmAlgorithm` doesn't see the internals so none of that should matter.

Anyway, that's the basic structure of the problem. If I try to run the same type of initialization with IL-SHADE (i.e. where the initial feasible points are known and that's what I want to initialize the population with); 

```[python]
    # Instantiate the problem
    task = Task(problem=MyProblem(), max_evals=3 if SMOKE_TEST else 1000)
    algo = ILSHADE.ImprovedLpsrSuccessHistoryAdaptiveDifferentialEvolution(
        population_size=len(train_X),
        initialization_function=init_with_configs, # Same structure as above MWE
        callbacks=[PrintBestFitness()],
        seed=42,
    )
```

then I get the error: 

```[python]
Traceback (most recent call last):
  File "il_shade.py", line 135, in <module>
    run(f)
  File "il_shade.py", line 122, in run
    best_x, best_fit = algo.run(task)  # Run once, for multiple runs stick in loop
  File "path/to/algorithm.py", line 321, in run
    raise e
  File "path/to/algorithm.py", line 314, in run
    pop, fpop, xb, fxb, params = self.run_iteration(task, pop, fpop, xb, fxb, **params)
  File "path/to/ilshade.py", line 343, in run_iteration
    new_population = self.evolve(sorted_pop, h_mem_cr, h_mem_f, archive, arc_ind_cnt, pbest_factor, task)
  File "path/to/ilshade.py", line 207, in evolve
    new_pop = objects_to_array([self.gen_ind_params(nfe, max_nfe, xi, hist_cr, hist_f) for xi in pop])
  File "path/to/ilshade.py", line 207, in <listcomp>
    new_pop = objects_to_array([self.gen_ind_params(nfe, max_nfe, xi, hist_cr, hist_f) for xi in pop])
  File "path/to/ilshade.py", line 187, in gen_ind_params
    return self.individual_type(x=x.x, differential_weight=f, crossover_probability=cr, e=False)
AttributeError: 'numpy.ndarray' object has no attribute 'x'
```

Here I just tried to initialize the population `pop`  with a known `np.ndarray` and `fpop` with a known `np.array` where `pop.shape[0] == len(fpop)`, like in the MWE above, but I get a very different behavior.

**System configuration**

 - OS: Apple M1 Max, macOS 14.7.1
 - Python version: 3.10.16

**Comment by neildhir** [comment]
Ended up having to do a bit of a hack, where my feasible points are found in `train_X:np.ndarray` and fitness values are found in `train_Y:np.ndarray`, with upper and lower bounds given as usual.

```[python]
    class DummyInit(Problem):
        def __init__(self):
            super().__init__(dimension=train_X.shape[1], lower=lower, upper=upper, name="DummyInit")

        def _evaluate(self, x):
            index = where((train_X == x).all(axis=1))[0][0]
            return train_Y[index, 0]

    # Custom initialization to enforce that IL-SHADE starts with feasible points
    dummy_task = Task(problem=DummyInit())

    def init_pop_individual(task, population_size, individual_type, **_kwargs):
        pop = objects_to_array([individual_type(x=xx, task=dummy_task) for xx in train_X])
        return pop, asarray([x.f for x in pop])
```

and then run the actual problem with

```[python]
    # Instantiate the problem
    task = Task(problem=MyRealProblem(), max_evals=5 if SMOKE_TEST else 1000, enable_logging=True)
    algo = ImprovedLpsrSuccessHistoryAdaptiveDifferentialEvolution(
        population_size=len(train_X),
        initialization_function=init_pop_individual,
        seed=42,
    )
```

This successfully initialises the iL-SHADE with real data points and the corresponding fitness values.

**Comment by neildhir** [comment]
Closing
